name: Test rbxlx-to-rojo
on:
  push:
    branches:
    - master
    - memothelemo/patch
  pull_request:
    branches:
    - master
    - memothelemo/patch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test